import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Brain, TrendingUp, AlertCircle, CheckCircle } from "lucide-react";

interface AIInsightsProps {
  userId: string;
}

const AIInsights = ({ userId }: AIInsightsProps) => {
  // Placeholder insights - in the future, these will be generated by AI
  const insights = [
    {
      id: 1,
      type: "positive",
      title: "Improved Recovery Pattern",
      description: "Your HRV shows a 15% improvement in recovery over the past week, particularly during sleep hours.",
      icon: CheckCircle,
      color: "text-stress-low",
    },
    {
      id: 2,
      type: "warning",
      title: "Elevated Afternoon Stress",
      description: "Stress levels tend to spike between 2-4 PM. Consider taking short breaks during this time.",
      icon: AlertCircle,
      color: "text-stress-moderate",
    },
    {
      id: 3,
      type: "trend",
      title: "Weekly Stress Trend",
      description: "Your average stress level decreased by 8% compared to last week. Great progress!",
      icon: TrendingUp,
      color: "text-primary",
    },
  ];

  return (
    <Card className="shadow-soft border-border/50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Brain className="h-5 w-5 text-primary" />
          AI-Generated Insights
        </CardTitle>
        <CardDescription>
          Automated analysis of your stress patterns and HRV trends
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {insights.map((insight) => (
          <div
            key={insight.id}
            className="flex gap-4 p-4 rounded-lg bg-muted/20 border border-border/50 hover:bg-muted/30 transition-colors"
          >
            <div className={`p-2 rounded-full bg-background h-fit ${insight.color}`}>
              <insight.icon className="h-5 w-5" />
            </div>
            <div className="flex-1 space-y-1">
              <div className="flex items-center gap-2">
                <h4 className="font-semibold text-sm">{insight.title}</h4>
                <Badge variant="outline" className="text-xs">
                  AI
                </Badge>
              </div>
              <p className="text-sm text-muted-foreground">{insight.description}</p>
            </div>
          </div>
        ))}
        
        <div className="mt-4 p-4 rounded-lg bg-primary/5 border border-primary/20">
          <p className="text-sm text-muted-foreground text-center">
            AI insights are continuously analyzing your data. More personalized recommendations will appear as more data is collected.
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default AIInsights;
